# Run normalization - Ariel
processDataset("xin-RowCount.csv", "linnorm")
processDataset("xin-RowCount.csv", "scran")
processDataset("xin-RowCount.csv", "tmm")
processDataset("xin-RowCount.csv", "scone")
processDataset("xin-RowCount.csv", "cpm")
processDataset("xin-RowCount.csv", "seurat")
processDataset("tasic-rpkms-RowCount.csv", "linnorm")
processDataset("tasic-rpkms-RowCount.csv", "scran")
processDataset("tasic-rpkms-RowCount.csv", "tmm")
processDataset("tasic-rpkms-RowCount.csv", "scone")
processDataset("tasic-rpkms-RowCount.csv", "cpm")
processDataset("tasic-rpkms-RowCount.csv", "seurat")