install.packages("BiocManager", repos = "http://cran.r-project.org")
BiocManager::install("Linnorm", force = TRUE)
BiocManager::install("edgeR", force = TRUE)
BiocManager::install("scone", force = TRUE)
install.packages("Seurat", repos = "http://cran.r-project.org")
